# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_logo',
        ),
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
